### ISSUE TITLE
(Request) SDR4space AppImage 

### ISSUE THREAD

**Issue by alphafox02** [SDR4space/FreeVersion#1]
SDR4space is an excellent application. I would like to request an AppImage. I think it would allow portability and a user to get up and running quickly across various Linux distributions. Having all requirements built in would be a plus. I’d love to include, when/if available, in DragonOS. 

Thank you.

**Comment by SDR4space** [comment]
Hello,

An AppImage is being tested and should be avalaible in few days ;)

**Comment by SDR4space** [comment]
Hi,

We just published a first version of our application packaged as AppImage.  
It only supports RTLSDR and PlutoSDR for the moment (be patient for other devices, sorry).
Feel free to downlad, try, and report issues.  

Go to 'releases' section : https://github.com/SDR4space/FreeVersion/releases/tag/v0.1  
Please take one minute to read warning related to AppImage use.  
This version is subject to be updated soon since we are fixing few bugs and improving processing tasks.
Keeping this issue open, thanks ...

**Comment by alphafox02** [comment]
That’s great news and excellent timing! I have both SDRs to test with. Will report any issues.
